-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE TELEFONE (
NUMERO VARCHAR(10),
IDTELEFONE VARCHAR(10) PRIMARY KEY,
DDD VARCHAR(10),
IDMEDICO VARCHAR(10),
IDPACIENTE VARCHAR(10)
)

CREATE TABLE MEDICO (
NOME VARCHAR(10),
SENHA VARCHAR(10),
EMAIL VARCHAR(10),
IDMEDICO VARCHAR(10) PRIMARY KEY,
IDPERFILACESSO VARCHAR(10),
IDESPECIALIDADE VARCHAR(10)
)

CREATE TABLE ESPECIALIDADE (
IDESPECIALIDADE VARCHAR(10) PRIMARY KEY,
NOME VARCHAR(10)
)

CREATE TABLE CONSULTA (
HORARIO VARCHAR(10),
IDCONSULTA VARCHAR(10) PRIMARY KEY,
IDMEDICO VARCHAR(10),
IDPACIENTE VARCHAR(10),
FOREIGN KEY(IDMEDICO) REFERENCES MEDICO (IDMEDICO)
)

CREATE TABLE PERFILACESSO (
CODIGO VARCHAR(10),
IDPERFILACESSO VARCHAR(10) PRIMARY KEY
)

CREATE TABLE PACIENTE (
IDPACIENTE VARCHAR(10) PRIMARY KEY,
EMAIL VARCHAR(10),
CPF VARCHAR(10),
SENHA VARCHAR(10),
NOME VARCHAR(10),
IDPERFILACESSO VARCHAR(10),
FOREIGN KEY(IDPERFILACESSO) REFERENCES PERFILACESSO (IDPERFILACESSO)
)

ALTER TABLE TELEFONE ADD FOREIGN KEY(IDMEDICO) REFERENCES MEDICO (IDMEDICO)
ALTER TABLE TELEFONE ADD FOREIGN KEY(IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE)
ALTER TABLE MEDICO ADD FOREIGN KEY(IDPERFILACESSO) REFERENCES PERFILACESSO (IDPERFILACESSO)
ALTER TABLE MEDICO ADD FOREIGN KEY(IDESPECIALIDADE) REFERENCES ESPECIALIDADE (IDESPECIALIDADE)
ALTER TABLE CONSULTA ADD FOREIGN KEY(IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE)
